os:
  - linux
  - osx
language: perl6
perl6:
  - latest
  - '2019.11'
  - '2020.02.1'
install:
  - rakudobrew build zef
  - zef install --deps-only --test-depends --/test .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr --ext .t --ext .t6 --ext .rakutest t
sudo: false
