defaults:
  steps:
    - checkout
    - run: tagged_release
version: 2
jobs:
  build:
    docker:
      - image: tonyodell/rakudo-nightly:latest
    
    working_directory: ~

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              zef install --deps-only --test-depends --/test .
      - run:
          name: test 
          command: |
              zef test .

